# Generated by Django 5.2.1 on 2025-05-09 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_client_address_alter_client_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='main.employee'),
        ),
    ]
