# Generated by Django 5.2.1 on 2025-05-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_tour_created_at_tour_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
