# Generated by Django 5.2.1 on 2025-05-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_faqentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('history', models.TextField()),
                ('founding_year', models.PositiveIntegerField()),
                ('requisites', models.TextField(help_text='Юридические реквизиты')),
            ],
        ),
    ]
